version: 2

defaults: &defaults
  working_directory: ~/device-protocol
  docker:
    - image: circleci/node

jobs:
  build:
    <<: *defaults
    docker:
      - image: safetyculture/protoc-node
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
      - run:
          name: Run build
          command: npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/device-protocol
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/device-protocol
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/device-protocol/.npmrc
      - run:
          name: Publish package
          command: npm publish
            
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/