version: 2

defaults: &defaults
  working_directory: ~/device-protocol
  docker:
    - image: circleci/node

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install protoc
          environment:
            PROTOBUF_VERSION: "3.5.1"
          command: >
            apt-get install -y sudo && \
            sudo apt-get update && \
            sudo apt-get install -y unzip git wget python3 && \
            rm -rf /var/lib/apt/lists/* && \
            wget https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip && \
            unzip protoc-${PROTOBUF_VERSION}-linux-x86_64.zip -d /usr/local && \
            rm protoc-${PROTOBUF_VERSION}-linux-x86_64.zip && \
            apt-get remove -y wget unzip && \
            apt-get autoremove -y
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install
      - run:
          name: Run build
          command: yarn build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/device-protocol
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/device-protocol
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/device-protocol/.npmrc
      - run:
          name: Publish package
          command: npm publish
            
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/